name: SCA
run-name: Scheduled SCA scan

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  sca:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write
      actions: read

    name: Execute ⚙️
    runs-on: ["ubuntu-latest"]
    needs: setup
    environment:
      name: ${{ needs.setup.outputs.environment }}

    steps:
      - name: Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: ⚡️ SCA
        uses: ministryofjustice/devsecops-actions/sca@9babea875cafae0e3b05a5ec5aca76d6b560c42e # v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Mandatory
          dependency-review-config-file: "./.github/dependency-review-config.yml" # Optional
