name: SCA test
run-name: Hello Kyle

on:
  push:

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: 🐷 TruffleHog
        uses: ./.github/actions/trufflehog   # ← path to your action
        with:
          trufflehog-config-file: .github/trufflehog-config.yaml; echo INJECTED
          trufflehog-output-filename: sca-trufflehog
